### ISSUE TITLE
File descriptor leak

### ISSUE THREAD

**Issue by wfvining** [mar-file-system/erasureUtils#10]
There is a file descriptor leak in `ne_close()` pointed out by Dave B.

The bug was introduced here d2e2175506ece7c06c92a4db0328e7b4bdf173f8. It effects reads and rebuilds only, writes are safe from the leak.

**Comment by jti-lanl** [comment]
In the event of errors, there may (conceivably) also have been some leaks via MarFS data_close() and marfs_flush(), which should be addressed by recent as-yet-uncommitted patches.

**Comment by wfvining** [comment]
Leak resolved. Watching the number of open files during a single-threaded rebuild shows that there are never more than 12 open throughout the rebuild.
