### ISSUE TITLE
remove small-writes for CRC

### ISSUE THREAD

**Issue by jti-lanl** [mar-file-system/erasureUtils#15]
In bq_writer(), we are currently sending the buffer and the CRC as distinct writes.  (There's a comment indicating this.)  I believe the CRC case already sizes the buffers to have room for the CRC tacked on at the end, and fills the rest of the buffer only up to there, to keep room for it.  If so, it would be a simple matter to just copy the CRC into the tail of the buf before sending.  I don't have time to check, just at the moment.  Making it an issue, so we can fix it eventually.  Should improve write performance.

**Comment by jti-lanl** [comment]
Confirmed that this is currently resulting in two distinct writes to ZFS, on the server side.  Perhaps we'd expect ZFS to coalesce these writes?

> [pid 45704] write(45, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 1048572 <unfinished ...>
> [pid 45704] <... write resumed> )       = 1048572
> [pid 45704] write(45, "\301f\240\301", 4) = 4

Two possible fixes (could do both):
* server should buffer until it has filled its buffer (or gotten EOF) and only write those buffers.
* client should coalesce these writes, as suggested originally.

**Comment by bws** [comment]
I think POSIX I/O writes can only be coalesced if the file space being
written to is preallocated.  I don't know the specific behavior of ZFS, but
XFS would aggressively coalesce under the direct I/O option with
pre-allocation.

**Comment by thewacokid** [comment]
All writes in ZFS are eligible for aggregation.  Direct I/O is not supported, nor is preallocation.


On Aug 17, 2017, at 10:44 AM, Brad Settlemyer <notifications@github.com<mailto:notifications@github.com>> wrote:

I think POSIX I/O writes can only be coalesced if the file space being
written to is preallocated. I don't know the specific behavior of ZFS, but
XFS would aggressively coalesce under the direct I/O option with
pre-allocation.

**Comment by bws** [comment]
I must be misunderstanding something.  It would be extremely difficult to
make combined writes and ENOSPC POSIX conforming if writes to unallocated
space could be combined.  Maybe this is some COW optimization I don't
understand very well.

**Comment by thewacokid** [comment]
In this case we’re talking about combining writes to the underlying disks.  They’re async writes into the ARC, then flushed explicitly through a sync call.  Anything in that transaction group can be combined when committed to disk, assuming there’s enough contiguous space to do so.

A good reference to the allocation process: https://blogs.oracle.com/roch/zero-copy-io-aggregation


On Aug 17, 2017, at 11:42 AM, Brad Settlemyer <notifications@github.com<mailto:notifications@github.com>> wrote:

I must be misunderstanding something. It would be extremely difficult to
make combined writes and ENOSPC POSIX conforming if writes to unallocated
space could be combined. Maybe this is some COW optimization I don't
understand very well.

**Comment by jti-lanl** [comment]
Thanks for the insight from both of you.

It would still no doubt be an improvement to cut the number of writes to the ARC in half.

**Comment by gransom** [comment]
Implemented as part of pull request #18.  Commit c67b76eb99afb46a8b1e670d78c27a2017744516.
I will close this issue after the merge is complete.

**Comment by gransom** [comment]
Threaded read pull request has been merged.  Closing this issue.
