### ISSUE TITLE
reading blocks twice, when INT_CRC is defined

### ISSUE THREAD

**Issue by jti-lanl** [mar-file-system/erasureUtils#6]
_[Developers are already aware of this.  Just capturing it here, so it won't slip through the cracks.]_

For all blocks except the first, in each stripe, it appears that there is a 1MB read, followed by a seek back to zero, then another 1MB read.

Read performance is already good, even with this issue.  Fixing it should make performance that much better.

**Comment by gransom** [comment]
It's been some time since I looked into this problem, but I believe that the rewrite of the ne_read() logic included in pull request #18 should avoid it.
I'll close this issue after the merge of that request is complete.

**Comment by gransom** [comment]
Pull request has been merged.  Closing this issue.
